In [33]:
import json
import re
from collections import defaultdict

CONFIG_FOLDER = '../src/config/'
DATA_FOLDER = '../data/'
TESTING_DATA_FOLDER = '../data/forTesting/'

esg_indicator_config_file_path = CONFIG_FOLDER + 'esg_indicator_standard_company_group_1.json'
esg_score_rule_file_path = CONFIG_FOLDER + 'esg_score_rules_group_1.json'

esg_company_file_path = TESTING_DATA_FOLDER + 'esg_company_1.json'


import pandas as pd
# pd.options.display.max_columns = 10
# pd.set_option('display.max_colwidth', None)

# Load the JSON data into a dictionary
# with open(config_file_path, 'r') as file:
#     esg_data_dict = json.load(file)

# print(esg_data_dict)

In [54]:
esg_data_dict = pd.read_json(esg_indicator_config_file_path)
esg_score_rules = pd.read_json(esg_score_rule_file_path)

with open(esg_company_file_path, 'r') as file:
    ec1 = json.load(file)
c1_df = pd.DataFrame(ec1['esg_context'])

esg_title_header = 'ESG report for ' + ec1['company_name'] + ' applied standard follow ' + ec1['esg_group'];

# print(esg_standard_df)
print(esg_title_header)
display(esg_data_dict)

display(esg_score_rules)
display(c1_df)
# display(c1_df[:1])

# def get_standard_by_key(key):
#     return esg_score_rules.query('metric_lable == @key') # filter(lambda o: o['metric_lable'] == key, esg_score_rules)[0]['standard_value']

# Function to get score based on metric_label and value
def get_score_by_metric(metric_label, value):
    print('===================metric_label:', metric_label)
    # print('esg_score_rules:', esg_score_rules)
    rules = esg_score_rules.loc[esg_score_rules['metric_label'] == metric_label] #.get(metric_label, [])
    print('======rules', rules)
    print('======value', value)
    for rule in rules:
        print('======rule checking', rule)
        if 'min_value' in rule and 'max_value' in rule:
            if rule['min_value'] <= value <= rule['max_value']:
                print('case1')
                return rule['score']
        elif 'max_value' in rule:
            if value <= rule['max_value']:
                print('case2')
                return rule['score']
        elif 'min_value' in rule:
            if value >= rule['min_value']:
                print('case3')
                return rule['score']
    print('case4')
    return None  # Or a default score if needed


# def get_indicator_score(input):
#     print(input)
#     rule = find_matched_rules(input['value'], get_standard_by_key(input['metric_lable']))
#     return rule['score']


# print(get_indicator_score(esg_data_dict[0]))
c1_df['score'] = c1_df.apply(lambda row: get_score_by_metric(row['metric_label'], row['value']), axis= 1)
display(c1_df)
# c1_with_score = c1_df

ESG report for CITI BANK applied standard follow GROUP_1

,subject_label,subject_name,topic_label,topic_name,metric_label,metric_name,stanrdard_value,unit,rules
0,E,Environment,E01_GHG,Greenhouse Gas Emissions,E01_GHG_01_TOTAL,Absolute emissions by total,1000,tCO2e,[greater is better]
1,E,Environment,E01_GHG,Greenhouse Gas Emissions,E01_GHG_02_TOTAL,Absolute emissions by Scope 1,1000,tCO2e,[greater is better]
2,E,Environment,E01_GHG,Greenhouse Gas Emissions,E01_GHG_03_TOTAL,Absolute emissions by Scope 2,1000,tCO2e,[lower is better]
3,E,Environment,E01_GHG,Greenhouse Gas Emissions,E01_GHG_04_TOTAL,Absolute emissions by Scope 3,1000,tCO2e,[greater is better]

,metric_label,standard_value,standard_score,unit,rules
0,E01_GHG_01_TOTAL,3000,10,tCO2e,"[{'min_value': 0, 'max_value': 2800, 'score': 10}, {'min_value': 2800, 'max_value': 3200, 'score': 9}, {'min_value': 3200, 'max_value': 3500, 'score': 5}, {'min_value': 3500, 'score': 1}]"
1,E01_GHG_02_TOTAL,1000,10,tCO2e,"[{'min_value': 0, 'max_value': 950, 'score': 10}, {'min_value': 950, 'max_value': 1050, 'score': 9}, {'min_value': 1050, 'max_value': 1150, 'score': 5}, {'min_value': 1150, 'score': 1}]"
2,E01_GHG_03_TOTAL,1000,10,tCO2e,"[{'min_value': 0, 'max_value': 950, 'score': 10}, {'min_value': 950, 'max_value': 1050, 'score': 9}, {'min_value': 1050, 'max_value': 1150, 'score': 5}, {'min_value': 1150, 'score': 1}]"
3,E01_GHG_04_TOTAL,1000,10,tCO2e,"[{'min_value': 0, 'max_value': 950, 'score': 10}, {'min_value': 950, 'max_value': 1050, 'score': 9}, {'min_value': 1050, 'max_value': 1150, 'score': 5}, {'min_value': 1150, 'score': 1}]"

       metric_label  value   unit
0  E01_GHG_01_TOTAL   3000  tCO2e
1  E01_GHG_02_TOTAL   1200  tCO2e
2  E01_GHG_03_TOTAL    950  tCO2e
3  E01_GHG_04_TOTAL    850  tCO2e

===================metric_label: E01_GHG_01_TOTAL
======rules        metric_label  standard_value  standard_score   unit  \
0  E01_GHG_01_TOTAL            3000              10  tCO2e

                                                                                                                                                                                         rules
0  [{'min_value': 0, 'max_value': 2800, 'score': 10}, {'min_value': 2800, 'max_value': 3200, 'score': 9}, {'min_value': 3200, 'max_value': 3500, 'score': 5}, {'min_value': 3500, 'score': 1}]
======value 3000
======rule checking metric_label
======rule checking standard_value
======rule checking standard_score
======rule checking unit
======rule checking rules
case4
===================metric_label: E01_GHG_02_TOTAL
======rules        metric_label  standard_value  standard_score   unit  \
1  E01_GHG_02_TOTAL            1000              10  tCO2e

                                                                                                                                                                                       rules
1  [{'min_value': 0, 'max_value': 950, 'score': 10}, {'min_value': 950, 'max_value': 1050, 'score': 9}, {'min_value': 1050, 'max_value': 1150, 'score': 5}, {'min_value': 1150, 'score': 1}]
======value 1200
======rule checking metric_label
======rule checking standard_value
======rule checking standard_score
======rule checking unit
======rule checking rules
case4
===================metric_label: E01_GHG_03_TOTAL
======rules        metric_label  standard_value  standard_score   unit  \
2  E01_GHG_03_TOTAL            1000              10  tCO2e

                                                                                                                                                                                       rules
2  [{'min_value': 0, 'max_value': 950, 'score': 10}, {'min_value': 950, 'max_value': 1050, 'score': 9}, {'min_value': 1050, 'max_value': 1150, 'score': 5}, {'min_value': 1150, 'score': 1}]
======value 950
======rule checking metric_label
======rule checking standard_value
======rule checking standard_score
======rule checking unit
======rule checking rules
case4
===================metric_label: E01_GHG_04_TOTAL
======rules        metric_label  standard_value  standard_score   unit  \
3  E01_GHG_04_TOTAL            1000              10  tCO2e

                                                                                                                                                                                       rules
3  [{'min_value': 0, 'max_value': 950, 'score': 10}, {'min_value': 950, 'max_value': 1050, 'score': 9}, {'min_value': 1050, 'max_value': 1150, 'score': 5}, {'min_value': 1150, 'score': 1}]
======value 850
======rule checking metric_label
======rule checking standard_value
======rule checking standard_score
======rule checking unit
======rule checking rules
case4

       metric_label  value   unit score
0  E01_GHG_01_TOTAL   3000  tCO2e  None
1  E01_GHG_02_TOTAL   1200  tCO2e  None
2  E01_GHG_03_TOTAL    950  tCO2e  None
3  E01_GHG_04_TOTAL    850  tCO2e  None